### ISSUE TITLE
Wording suggestion for Zeever/wiki

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/zeever#11]
Consider changing existing bullet to:

> To make this project work well with the features and methods of Backdrop CMS core and through development of this theme and it's associated module inspire improvements in Backdrop core.

**Comment by stpaultim** [comment]
@izmeez Sure, suggestion accepted. I kept the final part of that bullet point about NOT letting limitations in core block progress, because I think that is important. The goal of this project is to encourage improvements in core, while finding ways to work around existing limitations until they are fixed.

If you see anything in the Wiki that you can improve without substancially changing it's meaning, feel free to edit the Wiki directly. Feel free to add new content that you think would be helpful. 

I need to see if there is a way that I can get alerts on all changes to the wiki, so that I can verify that they do not take the project in a different direction. Otherwise, I do encourage people to edit the wiki themselves.

**Comment by stpaultim** [comment]
@izmeez Closing this ticket, because I think it's done. Feel free to reopen it if you have additional suggestions. Or, just make the changes to the wiki and alert me to which page you changed, so i can review the changes.
